### ISSUE TITLE
Add new method get_port

### ISSUE THREAD

**Issue by birdsarah** [mozilla/domain_utils#16]
Report back a port, if it was in the netloc.

**Comment by yabirgb** [comment]
What is the expected behave if there is no port in the netloc?

**Comment by birdsarah** [comment]
I think returning `None` is fine for now.

**Comment by birdsarah** [comment]
For context @yabirgb this is a library I'm actively using along with colleagues for now I'm happy to get a starting point for an API, put it in, see how it works in practice when doing analysis and tweak the API if necessary. My plan is to let everything bake for a few months and then move to 1.0 once we've stabilized and feel good about committing to an API.

**Comment by birdsarah** [comment]
> For context @yabirgb this is a library I'm actively using along with colleagues for now I'm happy to get a starting point for an API, put it in, see how it works in practice when doing analysis and tweak the API if necessary. 

If you're using the library, I'm also more than happy to hear your thoughts.

**Comment by birdsarah** [comment]
closed via #25
