### ISSUE TITLE
Edge cases in urlparse

### ISSUE THREAD

**Issue by yabirgb** [mozilla/domain_utils#23]
Trying to implement the `get_port` function I've found some cases where urllib fails to give what we want. 

For example trying to extract the port from `example.com:80/path/to/index.html` fails unless you prepend the schema to the url. 

Also in this case trying to extract the scheme returns `example.com` instead of `NO_SCHEME`.

I don't know if those are bugs in urllib or an intended behave. I'll suggest the use of regex but don't know if this is something desired by the team

**Comment by birdsarah** [comment]
yes, this is definitely a challenge. i’m happy enough with how its handled in get-stripped-url that i think for now we can just reuse that code. we may want to go to a regex later, but that code is short, its just the explanation that’s long.

check out the test cases for get-stripped-url. if there’s any that we’ve missed that you’ve come across while thinking about this, please open an issue.

**Comment by birdsarah** [comment]
Was on email and didn't realized you had opened a new issue here. I'm going to close this. Are you working on #16?

**Comment by birdsarah** [comment]
Also to clarify they're not bugs in urllib, they're the documented behavior.
